modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="CCSA3.0"

[[mods]] #mandatory
modId="scprotect" #mandatory
version="1.0.0-1.20.1" #mandatory
displayName="Secure Craft Protect" #mandatory
issueTrackerURL="https://github.com/Clockwork-Interactive/Secure-Craft-Protect/issues" #optional
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/Clockwork-Interactive/Secure-Craft-Protect" #optional
logoFile="logo.png" #optional
credits="Milkyfur, EveryWasTaken, Phoillows & the SCP wiki" #optional
authors="Sir.Pancakes, Zeus, YesMan2, SmollDave" #optional
description='''
Secure Craft Protect is a mod that adds in the anomalies known as SCP's from the SCP Foundation into Minecraft! Credit goes to the SCP Wiki :)
'''

[[dependencies.scprotect]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.scprotect]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
